import { Warden } from "warden-layout"

const defaultSkins:Warden.IMenuSkin[]=[
     {
        theme:"light",
        primaryColor:"#358cf1",
        name:"blueSky",
        label:"blueSky",
        backgroundImage:"/images/skins/blue-sky-bg.png",
        icon:"/images/skins/blue-sky-small.png"
    },{
        theme:"light",
        primaryColor:"#3a8ef7",
        name:"blueChristmas",       
        label:"blueChristmas",   
        backgroundImage:"/images/skins/blue-christmas-bg.png",
        icon:"/images/skins/blue-christmas-small.png"
    },
    {
        theme:"light",
        primaryColor:"#1d63b9",
        name:"blueLattice",
        label:"blueLattice",
        backgroundImage:"/images/skins/blue-lattice-bg-top.png,/images/skins/blue-lattice-bg-left.png",
        icon:"/images/skins/blue-lattice-small.png"
    },
    {
        theme:"light",
        primaryColor:"#ff677b",
        name:"pinkRomantic",
        label:"pinkRomantic",
        backgroundImage:"/images/skins/pink-romantic-bg.jpg",
        icon:"/images/skins/pink-romantic-small.jpg"
    },
    {
        theme:"light",
        primaryColor:"#4e9c48",
        layoutType:"leftMenu",
        menuByPrimary:false,
        name:"greenMountain",
        label:"greenMountain",
        backgroundImage:"/images/skins/green-mountain-bg.jpg",
        icon:"/images/skins/green-mountain-small.jpg"
    },
    {
        theme:"light",
        primaryColor:"#09a7e1",
        menuByPrimary:false,
        name:"paintSplashing",
        label:"paintSplashing",
        backgroundImage:"/images/skins/paint-splashing-bg-top.jpg,/images/skins/paint-splashing-bg-left.jpg",
        icon:"/images/skins/paint-splashing-small.jpg"
    },
    {
        theme:"light",
        primaryColor:"#eb591d",
        layoutType:"leftMenu",
        menuByPrimary:false,
        name:"orangeBubble",
        label:"orangeBubble",
        backgroundImage:"/images/skins/orange-bubble-bg.jpg",
        icon:"/images/skins/orange-bubble-small.jpg"
    },
    {
        theme:"dark",
        primaryColor:"#3987df",
        name:"starJellyfish",
        menuByPrimary:false,
        label:"starJellyfish",
        backgroundImage:"/images/skins/star-jellyfish-bg.jpg",
        icon:"/images/skins/star-jellyfish-small.jpg"
    },
    {
        theme:"dark",
        primaryColor:"#e53d32",
        name:"starNeon",
        label:"starNeon",
        backgroundImage:"/images/skins/star-neon-bg-top.jpg,/images/skins/star-neon-bg-left.jpg",
        icon:"/images/skins/star-neon-small.jpg"
    }
]


export {defaultSkins}
